/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Summarify API
 * API de transcription audio et de resume par IA
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  UploadAudioBody,
  UploadResponse
} from '../summarifyAPI.schemas';

import { customInstance } from '../../lib/axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Upload d'un fichier audio
 */
export type uploadAudioResponse200 = {
  data: UploadResponse
  status: 200
}

export type uploadAudioResponse413 = {
  data: ErrorResponse
  status: 413
}

export type uploadAudioResponseSuccess = (uploadAudioResponse200) & {
  headers: Headers;
};
export type uploadAudioResponseError = (uploadAudioResponse413) & {
  headers: Headers;
};

export type uploadAudioResponse = (uploadAudioResponseSuccess | uploadAudioResponseError)

export const getUploadAudioUrl = () => {




  return `/api/upload`
}

export const uploadAudio = async (uploadAudioBody: UploadAudioBody, options?: RequestInit): Promise<uploadAudioResponse> => {
    const formData = new FormData();
formData.append(`file`, uploadAudioBody.file);
if(uploadAudioBody.lang !== undefined) {
 formData.append(`lang`, uploadAudioBody.lang);
 }

  return customInstance<uploadAudioResponse>(getUploadAudioUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body:
      formData,
  }
);}




export const getUploadAudioMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadAudio>>, TError,{data: UploadAudioBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadAudio>>, TError,{data: UploadAudioBody}, TContext> => {

const mutationKey = ['uploadAudio'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadAudio>>, {data: UploadAudioBody}> = (props) => {
          const {data} = props ?? {};

          return  uploadAudio(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UploadAudioMutationResult = NonNullable<Awaited<ReturnType<typeof uploadAudio>>>
    export type UploadAudioMutationBody = UploadAudioBody
    export type UploadAudioMutationError = ErrorResponse

    /**
 * @summary Upload d'un fichier audio
 */
export const useUploadAudio = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadAudio>>, TError,{data: UploadAudioBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadAudio>>,
        TError,
        {data: UploadAudioBody},
        TContext
      > => {
      return useMutation(getUploadAudioMutationOptions(options), queryClient);
    }
    /**
 * Flux Server-Sent Events. Chaque event.data est un segment de texte.
Le flux se termine par l'event data: [DONE].
Supporte la reconnexion : les segments deja emis sont rejoues.

 * @summary Stream SSE de la transcription
 */
export type streamSessionResponse200 = {
  data: string
  status: 200
}

export type streamSessionResponse404 = {
  data: void
  status: 404
}

export type streamSessionResponseSuccess = (streamSessionResponse200) & {
  headers: Headers;
};
export type streamSessionResponseError = (streamSessionResponse404) & {
  headers: Headers;
};

export type streamSessionResponse = (streamSessionResponseSuccess | streamSessionResponseError)

export const getStreamSessionUrl = (sessionId: string,) => {




  return `/api/session/${sessionId}/stream`
}

export const streamSession = async (sessionId: string, options?: RequestInit): Promise<streamSessionResponse> => {

  return customInstance<streamSessionResponse>(getStreamSessionUrl(sessionId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getStreamSessionQueryKey = (sessionId: string,) => {
    return [
    `/api/session/${sessionId}/stream`
    ] as const;
    }


export const getStreamSessionQueryOptions = <TData = Awaited<ReturnType<typeof streamSession>>, TError = void>(sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof streamSession>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStreamSessionQueryKey(sessionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof streamSession>>> = ({ signal }) => streamSession(sessionId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(sessionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof streamSession>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StreamSessionQueryResult = NonNullable<Awaited<ReturnType<typeof streamSession>>>
export type StreamSessionQueryError = void


export function useStreamSession<TData = Awaited<ReturnType<typeof streamSession>>, TError = void>(
 sessionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof streamSession>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof streamSession>>,
          TError,
          Awaited<ReturnType<typeof streamSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStreamSession<TData = Awaited<ReturnType<typeof streamSession>>, TError = void>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof streamSession>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof streamSession>>,
          TError,
          Awaited<ReturnType<typeof streamSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStreamSession<TData = Awaited<ReturnType<typeof streamSession>>, TError = void>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof streamSession>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Stream SSE de la transcription
 */

export function useStreamSession<TData = Awaited<ReturnType<typeof streamSession>>, TError = void>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof streamSession>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStreamSessionQueryOptions(sessionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






