/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Summarify API
 * API de transcription audio et de resume par IA
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

/**
 * @summary Upload d'un fichier audio
 */
export const UploadAudioBody = zod.object({
  "file": zod.instanceof(File)
})

export const UploadAudioResponse = zod.object({
  "job_id": zod.uuid()
})


/**
 * Flux Server-Sent Events. Chaque event.data est un segment de texte.
Le flux se termine par l'event data: [DONE]

 * @summary Stream SSE de la transcription
 */
export const StreamTranscriptionParams = zod.object({
  "jobId": zod.uuid()
})

export const streamTranscriptionQueryLangRegExp = new RegExp('^[a-z]{2}$');


export const StreamTranscriptionQueryParams = zod.object({
  "lang": zod.string().regex(streamTranscriptionQueryLangRegExp).optional().describe('Code ISO 639-1 (fr, en, de…)')
})


/**
 * @summary Resume un texte via LLM
 */
export const summarizeTextBodyTextMin = 10;



export const SummarizeTextBody = zod.object({
  "text": zod.string().min(summarizeTextBodyTextMin).describe('Texte complet de la transcription a resumer')
})

export const SummarizeTextResponse = zod.object({
  "summary": zod.string().describe('Resume en 3 points cles genere par le LLM'),
  "model": zod.string().describe('Identifiant du modele LLM utilise (gpt-4o-mini ou qwen2.5:3b)')
})
