/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Summarify API
 * API de transcription audio et de resume par IA
 * OpenAPI spec version: 0.1.0
 */
export interface UploadResponse {
  session_id: string;
}

export interface SummarizeRequest {
  /**
     * Texte complet de la transcription a resumer
     * @minLength 10
     */
  text: string;
}

export interface SummarizeResponse {
  /** Resume en 3 points cles genere par le LLM */
  summary: string;
  /** Identifiant du modele LLM utilise (gpt-4o-mini ou qwen2.5:3b) */
  model: string;
}

export interface ErrorResponse {
  error: string;
}

export type UploadAudioBody = {
  /** Formats acceptes : mp3, wav, m4a, ogg, flac */
  file: Blob;
  /**
     * Code ISO 639-1 (fr, en…). Absent = auto-detection.
     * @pattern ^[a-z]{2}$
     */
  lang?: string;
};

