/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Summarify API
 * API de transcription audio et de resume par IA
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  SummarizeRequest,
  SummarizeResponse
} from '../summarifyAPI.schemas';

import { customInstance } from '../../lib/axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Resume un texte via LLM
 */
export type summarizeTextResponse200 = {
  data: SummarizeResponse
  status: 200
}

export type summarizeTextResponseSuccess = (summarizeTextResponse200) & {
  headers: Headers;
};
;

export type summarizeTextResponse = (summarizeTextResponseSuccess)

export const getSummarizeTextUrl = () => {




  return `/api/summarize`
}

export const summarizeText = async (summarizeRequest: SummarizeRequest, options?: RequestInit): Promise<summarizeTextResponse> => {

  return customInstance<summarizeTextResponse>(getSummarizeTextUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      summarizeRequest,)
  }
);}




export const getSummarizeTextMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof summarizeText>>, TError,{data: SummarizeRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof summarizeText>>, TError,{data: SummarizeRequest}, TContext> => {

const mutationKey = ['summarizeText'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof summarizeText>>, {data: SummarizeRequest}> = (props) => {
          const {data} = props ?? {};

          return  summarizeText(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SummarizeTextMutationResult = NonNullable<Awaited<ReturnType<typeof summarizeText>>>
    export type SummarizeTextMutationBody = SummarizeRequest
    export type SummarizeTextMutationError = unknown

    /**
 * @summary Resume un texte via LLM
 */
export const useSummarizeText = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof summarizeText>>, TError,{data: SummarizeRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof summarizeText>>,
        TError,
        {data: SummarizeRequest},
        TContext
      > => {
      return useMutation(getSummarizeTextMutationOptions(options), queryClient);
    }
